My POrg/src/objects/Object_1__c.object
<CustomObject>
    <fields>
        <fullName>Sales_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Object_1s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TestArea__c</fullName>
        <label>TestArea</label>
        <length>32500</length>
        <type>LongTextArea</type>
    </fields>
    <label>Object 1</label>
    <nameField>
        <label>Object 1 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Object 1s</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

My POrg/src/objects/Order_Counter__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Counter_Validator__c</fullName>
        <label>Counter Validator</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Order Counter</label>
</CustomObject>

My POrg/src/classes/DisplayObj.cls
public class DisplayObj{

    public List<Object_1__c> lstO {get;set;}
    public Opportunity opp;
    Public Id oId;
    public Decimal countValidator;
    
    
    public PageReference updateCounter() {
       countValidator=Order_Counter__c.getInstance('CounterId').Counter_Validator__c;
       return null;
    }
    
    public DisplayObj(ApexPages.StandardController controller) {
        opp = (Opportunity) controller.getRecord();
        oId=opp.Id;
        lstO=[Select Id,Sales_Rep__c,TestArea__c from Object_1__c limit 1];
    }
    
    public PageReference checkSession() {
       
       if(Order_Counter__c.getInstance('CounterId').Counter_Validator__c==countValidator){
           Order_Counter__c csUpdate=Order_Counter__c.getInstance('CounterId');
           csUpdate.Counter_Validator__c++;
           update csUpdate; 
           return null;
       }else{
           apexpages.Message msg = new Apexpages.Message(ApexPages.Severity.Info,'Record is already saved. Please refresh the page again');
           apexpages.addmessage(msg);
           return null;
       }
   }    
    
}